# Generated by Django 4.2.25 on 2025-10-14 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('active', 'Активне'), ('cancelled', 'Скасоване')], default='active', max_length=20),
        ),
    ]
