# Generated by Django 4.2.25 on 2025-10-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_product_name_alter_product_price_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='usage_instructions',
            field=models.TextField(blank=True, verbose_name='Спосіб використання'),
        ),
    ]
